### ISSUE TITLE
Inference time?

### ISSUE THREAD

**Issue by bryanbocao** [CIVA-Lab/Motion-U-Net#1]
Dear authors, this is a very interesting paper! May I know the inference time per frame or latency (ms per frame or FPS)? Thanks!

**Comment by GaniRahmon** [comment]
Thanks. 
The inference time for **Baseline/Highway** (_#frames: 1700, size: 320x240)_ -> **MU-Net1 (FPS) = 27.42** and **MU-Net2 (FPS) = 19.1.**
The inference time for **CameraJitter/Badminton** _(#frames: 1150, size: 720x480)_ -> **MU-Net1 (FPS) = 19.83** and **MU-Net2 (FPS) = 14.56.**
The inference was done on **NVIDIA GTX 1080Ti**.
