### ISSUE TITLE
Multi-modal implementation of MUNet2 regarding MoG2 and flux tensor.

### ISSUE THREAD

**Issue by Jedrekcangxin** [CIVA-Lab/Motion-U-Net#2]
Dear authors, this is a very interesting paper! 
I tried to apply this model to my project, but for the segmentation of MoG2 and the flux tensor method in MUNet2, I extensively searched for information and referred to the paper for code reproduction. However, the results were very poor, and I suspect that there are significant problems with my replication code. Could you provide the source code for these relevant parts? I would be very grateful!

**Comment by GaniRahmon** [comment]
Hi, 
Thank you for your interest in our work. I will upload the MoG2 part generation as soon as I can, however, the flux tensor part is not publicly available. And I don't have the privilege to share that part. But the flux tensor part is not hard to implement if you read the paper (flux tensor) in which it is explained in detail. 

The paper: 
F. Bunyak, K. Palaniappan, S. Nath, and G. Seetharaman, “Flux tensor constrained geodesic active contours
with sensor fusion for persistent object tracking,” Journal of Multimedia, vol. 2, no. 4, p. 20, 2007

**Comment by Jedrekcangxin** [comment]
Okay, thank you for your reply and look forward to your sharing.
