### ISSUE TITLE
flux mask

### ISSUE THREAD

**Issue by d556645fw** [CIVA-Lab/Motion-U-Net#3]
Dear author,This paper is interesting.I want to train my own dataset, how can I create flux mask?

**Comment by GaniRahmon** [comment]
Hi,
Thank you for your interest in our work. The flux tensor part is not publicly available. And I don't have the privilege to share that part. However, the flux tensor part is not hard to implement if you read the paper (flux tensor) in which it is explained in detail.

The paper:
F. Bunyak, K. Palaniappan, S. Nath, and G. Seetharaman, “Flux tensor constrained geodesic active contours
with sensor fusion for persistent object tracking,” Journal of Multimedia, vol. 2, no. 4, p. 20, 2007
